apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-post-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-post-app-service
  template:
    metadata:
      labels:
        app: rest-post-app-service
    spec:
      containers:
      - name: rest-post-app-service
        image: edowon0623/sample-post:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-sample-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest-sample-app
  template:
    metadata:
      labels:
        app: rest-sample-app
    spec:
      containers:
      - name: rest-sample-app
        image: edowon0623/sample-mybatis:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rest-post-app-service
  labels:
    app: rest-post-app-service
spec:
  ports:
    - name: "8080"
      port: 8082
      targetPort: 9999
  selector:
    app: rest-post-app-service
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: rest-sample-app-service
spec:
  ports:
    - name: "8080"
      port: 8081
      targetPort: 8888
  selector:
    app: rest-sample-app
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: service-loadbalancing
spec:
  rules:
  - http:
      paths:
        - path: /users
          backend:
            serviceName: rest-sample-app-service
            servicePort: 8081
        - path: /posts
          backend:
            serviceName: rest-post-app-service
            servicePort: 8082
