server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/k8sdb?serverTimezone=Asia/Seoul&allowMultiQueries=true
    username: k8suser
    password: k8suser
    driver-class-name: com.mysql.cj.jdbc.Driver

  devtools:
    restart:
      enabled: true

  application:
    name: rest-sample-app-service

  main:
    allow-bean-definition-overriding: true

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

#  h2:
#    console:
#      enabled: true
#      path: h2-console

mybatis:
  type-aliases-package: com.example.springbootmybatis.entity
  mapper-locations: mapper/**/*.xml

